Fixed phpstan errors
php-etl/rabbitmq-flow pull request #12
Opened 2023-11-22 10:42 UTC by sebprt

2023-11-23 13:15 UTC, clemzarch approved these changes

2023-11-23 13:25 UTC, JoMessina approved these changes

2023-11-23 13:31 UTC, JoMessina reviewed
Remarque concernant les workflow github. Sur l'action phpstan 5 dans quality tu set un php_version qui n'est pas fait ailleurs. Est-ce obligatoire ou pas ? Il faut peut-être normaliser ici.

2023-11-23 14:19 UTC, sebprt commented
> Remarque concernant les workflow github. Sur l'action phpstan 5 dans quality tu set un php_version qui n'est pas fait ailleurs. Est-ce obligatoire ou pas ? Il faut peut-être normaliser ici.

Je vais supprimer cette option, afin d'avoir la même chose sur toutes les actions. D'autant plus  que la version est définie juste avant

2023-11-24 09:28 UTC, JoMessina approved these changes

2023-11-24 09:30 UTC, JoMessina approved these changes

2023-11-24 10:26 UTC, gplanchat requested changes

2023-11-24 10:26 UTC, gplanchat commented on src/Loader.php
> +        int $port = null,
Il y a un souci de config dans CS-Fixer. J'aimerais conserver la précision explicite du nullable dans le type.

2023-11-24 10:26 UTC, gplanchat commented on src/StateManager.php
> +                'id' => uuid_create(UUID_TYPE_RANDOM),
Est-ce qu'on peut vérifier les règles de CS-Fixer pour ne pas retirer les slash ?

2023-11-29 15:22 UTC, sebprt commented on src/Loader.php
> +        int $port = null,
Pas de soucis, j'ai ajouté l'option `nullable_type_declaration_for_default_null_value` dans la config php-cs-fixer

2023-11-29 15:25 UTC, sebprt commented on src/StateManager.php
> +                'id' => uuid_create(UUID_TYPE_RANDOM),
J'ai ajouté ceci dans la configuration pour conserver les `\` devant les fonctions et les constantes

```
'native_function_invocation' => [
    'include' => ['@all'],
],
'native_constant_invocation' => [
    'include' => ['@all'],
],
```

2023-12-19 20:25 UTC, gplanchat requested changes

2023-12-19 20:25 UTC, gplanchat commented on src/Loader.php
> +        $line = new EmptyResultBucket();
il manque un `yield` ici

2023-12-20 08:07 UTC, sebprt commented on src/Loader.php
> +        $line = new EmptyResultBucket();
Effectivement, c'est rajouté

2023-12-22 08:04 UTC, merged